// © ickk 2023-2026, All Rights Reserved.

use {
  crate::{
    macros::{make_device_features, make_extensions},
    queue_requirements::QueueRequirements,
  },
  ::ash::vk::PhysicalDeviceType,
};

#[derive(Default)]
pub struct DeviceRequirements<'device_name, 'queue_names> {
  pub device_name_substr: &'device_name str,
  pub device_type: Option<DeviceType>,
  pub features: Features,
  pub extensions: DeviceExtensions,
  pub queues: Vec<QueueRequirements<'queue_names>>,
}

#[derive(Copy, Clone, Debug)]
pub enum DeviceType {
  Other,
  Integrated,
  Discrete,
  Virtual,
  Cpu,
}

impl From<DeviceType> for PhysicalDeviceType {
  #[inline]
  fn from(device_type: DeviceType) -> Self {
    match device_type {
      DeviceType::Other => PhysicalDeviceType::OTHER,
      DeviceType::Integrated => PhysicalDeviceType::INTEGRATED_GPU,
      DeviceType::Discrete => PhysicalDeviceType::DISCRETE_GPU,
      DeviceType::Virtual => PhysicalDeviceType::VIRTUAL_GPU,
      DeviceType::Cpu => PhysicalDeviceType::CPU,
    }
  }
}

make_device_features! {
  features10: {
    robust_buffer_access,
    full_draw_index_uint32,
    image_cube_array,
    independent_blend,
    geometry_shader,
    tessellation_shader,
    sample_rate_shading,
    dual_src_blend,
    logic_op,
    multi_draw_indirect,
    draw_indirect_first_instance,
    depth_clamp,
    depth_bias_clamp,
    fill_mode_non_solid,
    depth_bounds,
    wide_lines,
    large_points,
    alpha_to_one,
    multi_viewport,
    sampler_anisotropy,
    texture_compression_etc2,
    texture_compression_astc_ldr,
    texture_compression_bc,
    occlusion_query_precise,
    pipeline_statistics_query,
    vertex_pipeline_stores_and_atomics,
    fragment_stores_and_atomics,
    shader_tessellation_and_geometry_point_size,
    shader_image_gather_extended,
    shader_storage_image_extended_formats,
    shader_storage_image_multisample,
    shader_storage_image_read_without_format,
    shader_storage_image_write_without_format,
    shader_uniform_buffer_array_dynamic_indexing,
    shader_sampled_image_array_dynamic_indexing,
    shader_storage_buffer_array_dynamic_indexing,
    shader_storage_image_array_dynamic_indexing,
    shader_clip_distance,
    shader_cull_distance,
    shader_float64,
    shader_int64,
    shader_int16,
    shader_resource_residency,
    shader_resource_min_lod,
    sparse_binding,
    sparse_residency_buffer,
    sparse_residency_image2_d,
    sparse_residency_image3_d,
    sparse_residency2_samples,
    sparse_residency4_samples,
    sparse_residency8_samples,
    sparse_residency16_samples,
    sparse_residency_aliased,
    variable_multisample_rate,
    inherited_queries,
  }
  features11: {
    storage_buffer16_bit_access,
    uniform_and_storage_buffer16_bit_access,
    storage_push_constant16,
    storage_input_output16,
    multiview,
    multiview_geometry_shader,
    multiview_tessellation_shader,
    variable_pointers_storage_buffer,
    variable_pointers,
    protected_memory,
    sampler_ycbcr_conversion,
    shader_draw_parameters,
  }
  features12: {
    sampler_mirror_clamp_to_edge,
    draw_indirect_count,
    storage_buffer8_bit_access,
    uniform_and_storage_buffer8_bit_access,
    storage_push_constant8,
    shader_buffer_int64_atomics,
    shader_shared_int64_atomics,
    shader_float16,
    shader_int8,
    descriptor_indexing,
    shader_input_attachment_array_dynamic_indexing,
    shader_uniform_texel_buffer_array_dynamic_indexing,
    shader_storage_texel_buffer_array_dynamic_indexing,
    shader_uniform_buffer_array_non_uniform_indexing,
    shader_sampled_image_array_non_uniform_indexing,
    shader_storage_buffer_array_non_uniform_indexing,
    shader_storage_image_array_non_uniform_indexing,
    shader_input_attachment_array_non_uniform_indexing,
    shader_uniform_texel_buffer_array_non_uniform_indexing,
    shader_storage_texel_buffer_array_non_uniform_indexing,
    descriptor_binding_uniform_buffer_update_after_bind,
    descriptor_binding_sampled_image_update_after_bind,
    descriptor_binding_storage_image_update_after_bind,
    descriptor_binding_storage_buffer_update_after_bind,
    descriptor_binding_uniform_texel_buffer_update_after_bind,
    descriptor_binding_storage_texel_buffer_update_after_bind,
    descriptor_binding_update_unused_while_pending,
    descriptor_binding_partially_bound,
    descriptor_binding_variable_descriptor_count,
    runtime_descriptor_array,
    sampler_filter_minmax,
    scalar_block_layout,
    imageless_framebuffer,
    uniform_buffer_standard_layout,
    shader_subgroup_extended_types,
    separate_depth_stencil_layouts,
    host_query_reset,
    timeline_semaphore,
    buffer_device_address,
    buffer_device_address_capture_replay,
    buffer_device_address_multi_device,
    vulkan_memory_model,
    vulkan_memory_model_device_scope,
    vulkan_memory_model_availability_visibility_chains,
    shader_output_viewport_index,
    shader_output_layer,
    subgroup_broadcast_dynamic_id,
  }
  features13: {
    robust_image_access,
    inline_uniform_block,
    descriptor_binding_inline_uniform_block_update_after_bind,
    pipeline_creation_cache_control,
    private_data,
    shader_demote_to_helper_invocation,
    shader_terminate_invocation,
    subgroup_size_control,
    compute_full_subgroups,
    synchronization2,
    texture_compression_astc_hdr,
    shader_zero_initialize_workgroup_memory,
    dynamic_rendering,
    shader_integer_dot_product,
    maintenance4,
  }
  khr_fragment_shader_barycentric: {
    fragment_shader_barycentric,
  }
}

make_extensions! {
  pub DeviceExtensions {
    khr_acceleration_structure: cr"VK_KHR_acceleration_structure",
    khr_calibrated_timestamps: cr"VK_KHR_calibrated_timestamps",
    khr_cooperative_matrix: cr"VK_KHR_cooperative_matrix",
    khr_deferred_host_operations: cr"VK_KHR_deferred_host_operations",
    khr_display_swapchain: cr"VK_KHR_display_swapchain",
    khr_external_fence_fd: cr"VK_KHR_external_fence_fd",
    khr_external_fence_win32: cr"VK_KHR_external_fence_win32",
    khr_external_memory_fd: cr"VK_KHR_external_memory_fd",
    khr_external_memory_win32: cr"VK_KHR_external_memory_win32",
    khr_external_semaphore_fd: cr"VK_KHR_external_semaphore_fd",
    khr_external_semaphore_win32: cr"VK_KHR_external_semaphore_win32",
    khr_fragment_shader_barycentric: cr"VK_KHR_fragment_shader_barycentric",
    khr_fragment_shading_rate: cr"VK_KHR_fragment_shading_rate",
    khr_global_priority: cr"VK_KHR_global_priority",
    khr_incremental_present: cr"VK_KHR_incremental_present",
    khr_maintenance5: cr"VK_KHR_maintenance5",
    khr_maintenance6: cr"VK_KHR_maintenance6",
    khr_map_memory2: cr"VK_KHR_map_memory2",
    khr_performance_query: cr"VK_KHR_performance_query",
    khr_pipeline_executable_properties: cr"VK_KHR_pipeline_executable_properties",
    khr_pipeline_library: cr"VK_KHR_pipeline_library",
    khr_present_id: cr"VK_KHR_present_id",
    khr_present_wait: cr"VK_KHR_present_wait",
    khr_push_descriptor: cr"VK_KHR_push_descriptor",
    khr_ray_query: cr"VK_KHR_ray_query",
    khr_ray_tracing_maintenance1: cr"VK_KHR_ray_tracing_maintenance1",
    khr_ray_tracing_pipeline: cr"VK_KHR_ray_tracing_pipeline",
    khr_ray_tracing_position_fetch: cr"VK_KHR_ray_tracing_position_fetch",
    khr_shader_clock: cr"VK_KHR_shader_clock",
    khr_shader_subgroup_uniform_control_flow: cr"VK_KHR_shader_subgroup_uniform_control_flow",
    khr_shared_presentable_image: cr"VK_KHR_shared_presentable_image",
    khr_swapchain: cr"VK_KHR_swapchain",
    khr_swapchain_mutable_format: cr"VK_KHR_swapchain_mutable_format",
    khr_vertex_attribute_divisor: cr"VK_KHR_vertex_attribute_divisor",
    khr_video_decode_h264: cr"VK_KHR_video_decode_h264",
    khr_video_decode_h265: cr"VK_KHR_video_decode_h265",
    khr_video_decode_queue: cr"VK_KHR_video_decode_queue",
    khr_video_encode_h264: cr"VK_KHR_video_encode_h264",
    khr_video_encode_h265: cr"VK_KHR_video_encode_h265",
    khr_video_encode_queue: cr"VK_KHR_video_encode_queue",
    khr_video_maintenance1: cr"VK_KHR_video_maintenance1",
    khr_video_queue: cr"VK_KHR_video_queue",
    khr_win32_keyed_mutex: cr"VK_KHR_win32_keyed_mutex",
    khr_workgroup_memory_explicit_layout: cr"VK_KHR_workgroup_memory_explicit_layout",
    ext_astc_decode_mode: cr"VK_EXT_astc_decode_mode",
    ext_attachment_feedback_loop_dynamic_state: cr"VK_EXT_attachment_feedback_loop_dynamic_state",
    ext_attachment_feedback_loop_layout: cr"VK_EXT_attachment_feedback_loop_layout",
    ext_blend_operation_advanced: cr"VK_EXT_blend_operation_advanced",
    ext_border_color_swizzle: cr"VK_EXT_border_color_swizzle",
    ext_color_write_enable: cr"VK_EXT_color_write_enable",
    ext_conditional_rendering: cr"VK_EXT_conditional_rendering",
    ext_conservative_rasterization: cr"VK_EXT_conservative_rasterization",
    ext_custom_border_color: cr"VK_EXT_custom_border_color",
    ext_depth_bias_control: cr"VK_EXT_depth_bias_control",
    ext_depth_clamp_zero_one: cr"VK_EXT_depth_clamp_zero_one",
    ext_depth_clip_control: cr"VK_EXT_depth_clip_control",
    ext_depth_clip_enable: cr"VK_EXT_depth_clip_enable",
    ext_depth_range_unrestricted: cr"VK_EXT_depth_range_unrestricted",
    ext_descriptor_buffer: cr"VK_EXT_descriptor_buffer",
    ext_device_address_binding_report: cr"VK_EXT_device_address_binding_report",
    ext_device_fault: cr"VK_EXT_device_fault",
    ext_device_memory_report: cr"VK_EXT_device_memory_report",
    ext_discard_rectangles: cr"VK_EXT_discard_rectangles",
    ext_display_control: cr"VK_EXT_display_control",
    ext_dynamic_rendering_unused_attachments: cr"VK_EXT_dynamic_rendering_unused_attachments",
    ext_extended_dynamic_state3: cr"VK_EXT_extended_dynamic_state3",
    ext_external_memory_acquire_unmodified: cr"VK_EXT_external_memory_acquire_unmodified",
    ext_external_memory_dma_buf: cr"VK_EXT_external_memory_dma_buf",
    ext_external_memory_host: cr"VK_EXT_external_memory_host",
    ext_filter_cubic: cr"VK_EXT_filter_cubic",
    ext_fragment_density_map: cr"VK_EXT_fragment_density_map",
    ext_fragment_density_map2: cr"VK_EXT_fragment_density_map2",
    ext_fragment_shader_interlock: cr"VK_EXT_fragment_shader_interlock",
    ext_frame_boundary: cr"VK_EXT_frame_boundary",
    ext_full_screen_exclusive: cr"VK_EXT_full_screen_exclusive",
    ext_graphics_pipeline_library: cr"VK_EXT_graphics_pipeline_library",
    ext_hdr_metadata: cr"VK_EXT_hdr_metadata",
    ext_host_image_copy: cr"VK_EXT_host_image_copy",
    ext_image_2d_view_of_3d: cr"VK_EXT_image_2d_view_of_3d",
    ext_image_compression_control: cr"VK_EXT_image_compression_control",
    ext_image_compression_control_swapchain: cr"VK_EXT_image_compression_control_swapchain",
    ext_image_drm_format_modifier: cr"VK_EXT_image_drm_format_modifier",
    ext_image_sliced_view_of_3d: cr"VK_EXT_image_sliced_view_of_3d",
    ext_image_view_min_lod: cr"VK_EXT_image_view_min_lod",
    ext_index_type_uint8: cr"VK_EXT_index_type_uint8",
    ext_legacy_dithering: cr"VK_EXT_legacy_dithering",
    ext_line_rasterization: cr"VK_EXT_line_rasterization",
    ext_load_store_op_none: cr"VK_EXT_load_store_op_none",
    ext_memory_budget: cr"VK_EXT_memory_budget",
    ext_memory_priority: cr"VK_EXT_memory_priority",
    ext_mesh_shader: cr"VK_EXT_mesh_shader",
    ext_metal_objects: cr"VK_EXT_metal_objects",
    ext_multi_draw: cr"VK_EXT_multi_draw",
    ext_multisampled_render_to_single_sampled: cr"VK_EXT_multisampled_render_to_single_sampled",
    ext_mutable_descriptor_type: cr"VK_EXT_mutable_descriptor_type",
    ext_nested_command_buffer: cr"VK_EXT_nested_command_buffer",
    ext_non_seamless_cube_map: cr"VK_EXT_non_seamless_cube_map",
    ext_opacity_micromap: cr"VK_EXT_opacity_micromap",
    ext_pageable_device_local_memory: cr"VK_EXT_pageable_device_local_memory",
    ext_pci_bus_info: cr"VK_EXT_pci_bus_info",
    ext_physical_device_drm: cr"VK_EXT_physical_device_drm",
    ext_pipeline_library_group_handles: cr"VK_EXT_pipeline_library_group_handles",
    ext_pipeline_properties: cr"VK_EXT_pipeline_properties",
    ext_pipeline_protected_access: cr"VK_EXT_pipeline_protected_access",
    ext_pipeline_robustness: cr"VK_EXT_pipeline_robustness",
    ext_post_depth_coverage: cr"VK_EXT_post_depth_coverage",
    ext_primitive_topology_list_restart: cr"VK_EXT_primitive_topology_list_restart",
    ext_primitives_generated_query: cr"VK_EXT_primitives_generated_query",
    ext_provoking_vertex: cr"VK_EXT_provoking_vertex",
    ext_queue_family_foreign: cr"VK_EXT_queue_family_foreign",
    ext_rasterization_order_attachment_access: cr"VK_EXT_rasterization_order_attachment_access",
    ext_rgba10x6_formats: cr"VK_EXT_rgba10x6_formats",
    ext_robustness2: cr"VK_EXT_robustness2",
    ext_sample_locations: cr"VK_EXT_sample_locations",
    ext_shader_atomic_float: cr"VK_EXT_shader_atomic_float",
    ext_shader_atomic_float2: cr"VK_EXT_shader_atomic_float2",
    ext_shader_image_atomic_int64: cr"VK_EXT_shader_image_atomic_int64",
    ext_shader_module_identifier: cr"VK_EXT_shader_module_identifier",
    ext_shader_object: cr"VK_EXT_shader_object",
    ext_shader_stencil_export: cr"VK_EXT_shader_stencil_export",
    ext_shader_tile_image: cr"VK_EXT_shader_tile_image",
    ext_subpass_merge_feedback: cr"VK_EXT_subpass_merge_feedback",
    ext_swapchain_maintenance1: cr"VK_EXT_swapchain_maintenance1",
    ext_transform_feedback: cr"VK_EXT_transform_feedback",
    ext_validation_cache: cr"VK_EXT_validation_cache",
    ext_vertex_input_dynamic_state: cr"VK_EXT_vertex_input_dynamic_state",
    ext_ycbcr_image_arrays: cr"VK_EXT_ycbcr_image_arrays",
    amd_buffer_marker: cr"VK_AMD_buffer_marker",
    amd_device_coherent_memory: cr"VK_AMD_device_coherent_memory",
    amd_display_native_hdr: cr"VK_AMD_display_native_hdr",
    amd_gcn_shader: cr"VK_AMD_gcn_shader",
    amd_memory_overallocation_behavior: cr"VK_AMD_memory_overallocation_behavior",
    amd_mixed_attachment_samples: cr"VK_AMD_mixed_attachment_samples",
    amd_pipeline_compiler_control: cr"VK_AMD_pipeline_compiler_control",
    amd_rasterization_order: cr"VK_AMD_rasterization_order",
    amd_shader_ballot: cr"VK_AMD_shader_ballot",
    amd_shader_core_properties: cr"VK_AMD_shader_core_properties",
    amd_shader_core_properties2: cr"VK_AMD_shader_core_properties2",
    amd_shader_early_and_late_fragment_tests: cr"VK_AMD_shader_early_and_late_fragment_tests",
    amd_shader_explicit_vertex_parameter: cr"VK_AMD_shader_explicit_vertex_parameter",
    amd_shader_fragment_mask: cr"VK_AMD_shader_fragment_mask",
    amd_shader_image_load_store_lod: cr"VK_AMD_shader_image_load_store_lod",
    amd_shader_info: cr"VK_AMD_shader_info",
    amd_shader_trinary_minmax: cr"VK_AMD_shader_trinary_minmax",
    amd_texture_gather_bias_lod: cr"VK_AMD_texture_gather_bias_lod",
    android_external_format_resolve: cr"VK_ANDROIND_external_format_resolve",
    android_external_memory_android_hardware_buffer: cr"VK_ANDROIND_external_memory_android_hardware_buffer",
    arm_render_pass_striped: cr"VK_ARM_render_pass_striped",
    arm_scheduling_controls: cr"VK_ARM_scheduling_controls",
    arm_shader_core_builtins: cr"VK_ARM_shader_core_builtins",
    arm_shader_core_properties: cr"VK_ARM_shader_core_properties",
    fuchsia_buffer_collection: cr"VK_FUCHSIA_buffer_collection",
    fuchsia_external_memory: cr"VK_FUCHSIA_external_memory",
    fuchsia_external_semaphore: cr"VK_FUCHSIA_external_semaphore",
    ggp_frame_token: cr"VK_GGP_frame_token",
    google_decorate_string: cr"VK_GOOGLE_decorate_string",
    google_display_timing: cr"VK_GOOGLE_display_timing",
    google_hlsl_functionality1: cr"VK_GOOGLE_hlsl_functionality1",
    google_user_type: cr"VK_GOOGLE_user_type",
    huawei_cluster_culling_shader: cr"VK_HUAWEI_cluster_culling_shader",
    huawei_invocation_mask: cr"VK_HUAWEI_invocation_mask",
    huawei_subpass_shading: cr"VK_HUAWEI_subpass_shading",
    img_filter_cubic: cr"VK_IMG_filter_cubic",
    img_relaxed_line_rasterization: cr"VK_IMG_relaxed_line_rasterization",
    intel_performance_query: cr"VK_INTEL_performance_query",
    intel_shader_integer_functions2: cr"VK_INTEL_shader_integer_functions2",
    msft_layered_driver: cr"VK_MSFT_layered_driver",
    nv_acquire_winrt_display: cr"VK_NV_acquire_winrt_display",
    nv_clip_space_w_scaling: cr"VK_NV_clip_space_w_scaling",
    nv_compute_shader_derivatives: cr"VK_NV_compute_shader_derivatives",
    nv_cooperative_matrix: cr"VK_NV_cooperative_matrix",
    nv_copy_memory_indirect: cr"VK_NV_copy_memory_indirect",
    nv_corner_sampled_image: cr"VK_NV_corner_sampled_image",
    nv_coverage_reduction_mode: cr"VK_NV_coverage_reduction_mode",
    nv_dedicated_allocation_image_aliasing: cr"VK_NV_dedicated_allocation_image_aliasing",
    nv_descriptor_pool_overallocation: cr"VK_NV_descriptor_pool_overallocation",
    nv_device_diagnostic_checkpoints: cr"VK_NV_device_diagnostic_checkpoints",
    nv_device_diagnostics_config: cr"VK_NV_device_diagnostics_config",
    nv_device_generated_commands: cr"VK_NV_device_generated_commands",
    nv_device_generated_commands_compute: cr"VK_NV_device_generated_commands_compute",
    nv_extended_sparse_address_space: cr"VK_NV_extended_sparse_address_space",
    nv_external_memory_rdma: cr"VK_NV_external_memory_rdma",
    nv_fill_rectangle: cr"VK_NV_fill_rectangle",
    nv_fragment_coverage_to_color: cr"VK_NV_fragment_coverage_to_color",
    nv_fragment_shading_rate_enums: cr"VK_NV_fragment_shading_rate_enums",
    nv_framebuffer_mixed_samples: cr"VK_NV_framebuffer_mixed_samples",
    nv_geometry_shader_passthrough: cr"VK_NV_geometry_shader_passthrough",
    nv_inherited_viewport_scissor: cr"VK_NV_inherited_viewport_scissor",
    nv_linear_color_attachment: cr"VK_NV_linear_color_attachment",
    nv_low_latency: cr"VK_NV_low_latency",
    nv_low_latency2: cr"VK_NV_low_latency2",
    nv_memory_decompression: cr"VK_NV_memory_decompression",
    nv_mesh_shader: cr"VK_NV_mesh_shader",
    nv_optical_flow: cr"VK_NV_optical_flow",
    nv_per_stage_descriptor_set: cr"VK_NV_per_stage_descriptor_set",
    nv_present_barrier: cr"VK_NV_present_barrier",
    nv_ray_tracing: cr"VK_NV_ray_tracing",
    nv_ray_tracing_invocation_reorder: cr"VK_NV_ray_tracing_invocation_reorder",
    nv_ray_tracing_motion_blur: cr"VK_NV_ray_tracing_motion_blur",
    nv_representative_fragment_test: cr"VK_NV_representative_fragment_test",
    nv_sample_mask_override_coverage: cr"VK_NV_sample_mask_override_coverage",
    nv_scissor_exclusive: cr"VK_NV_scissor_exclusive",
    nv_shader_image_footprint: cr"VK_NV_shader_image_footprint",
    nv_shader_sm_builtins: cr"VK_NV_shader_sm_builtins",
    nv_shader_subgroup_partitioned: cr"VK_NV_shader_subgroup_partitioned",
    nv_shading_rate_image: cr"VK_NV_shading_rate_image",
    nv_viewport_array2: cr"VK_NV_viewport_array2",
    nv_viewport_swizzle: cr"VK_NV_viewport_swizzle",
    nvx_binary_import: cr"VK_NVX_binary_import",
    nvx_image_view_handle: cr"VK_NVX_image_view_handle",
    nvx_multiview_per_view_attributes: cr"VK_NVX_multiview_per_view_attributes",
    qcom_filter_cubic_clamp: cr"VK_QCOM_filter_cubic_clamp",
    qcom_filter_cubic_weights: cr"VK_QCOM_filter_cubic_weights",
    qcom_fragment_density_map_offset: cr"VK_QCOM_fragment_density_map_offset",
    qcom_image_processing: cr"VK_QCOM_image_processing",
    qcom_image_processing2: cr"VK_QCOM_image_processing2",
    qcom_multiview_per_view_render_areas: cr"VK_QCOM_multiview_per_view_render_areas",
    qcom_multiview_per_view_viewports: cr"VK_QCOM_multiview_per_view_viewports",
    qcom_render_pass_shader_resolve: cr"VK_QCOM_render_pass_shader_resolve",
    qcom_render_pass_store_ops: cr"VK_QCOM_render_pass_store_ops",
    qcom_render_pass_transform: cr"VK_QCOM_render_pass_transform",
    qcom_rotated_copy_commands: cr"VK_QCOM_rotated_copy_commands",
    qcom_tile_properties: cr"VK_QCOM_tile_properties",
    qcom_ycbcr_degamma: cr"VK_QCOM_ycbcr_degamma",
    qnx_external_memory_screen_buffer: cr"VK_QNX_external_memory_screen_buffer",
    sec_amigo_profiling: cr"VK_SEC_amigo_profiling",
    valve_descriptor_set_host_mapping: cr"VK_VALVE_descriptor_set_host_mapping",
  }
}
