# © ickk 2023-2026, All Rights Reserved.

[package]
name = "ash-init"
authors = ["ickk <crates@ickk.io>"]
version = "0.0.0"
edition = "2021"
description = "Vulkan Instance & Device bootstrapping"
publish = false

[dependencies]
ash = { workspace = true, features = ["loaded", "debug"] }
raw-window-handle = { workspace = true, features = ["std"] }
tracing = { workspace = true, optional = true }
xcb = { workspace = true, optional = true }
x11 = { workspace = true, optional = true }

[features]
default = ["tracing"]
xcb = ["dep:xcb"]
xlib = ["dep:x11", "x11/xlib"]
# enables `TracingDebugCallback` impl
tracing = ["dep:tracing"]

[lints]
workspace = true
